### ISSUE TITLE
Frozen column is missing drop shadow

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/expense-manager-demo#6] opened 2015-12-11 08:50 UTC
To make it more clear for mobile users that they can scroll the grid also horizontally, the frozen column should at least have the drop shadow to the light as in the attached example. The horizontal 1px lines added between rows in the demo might make the light shadow less noticeable so I might try removing the lines as in the original design. If a more visible zebra contrast between lines is needed for poor displays, then try a bit darker grey background for the altering rows.
![iphone 6 - overview - total - teal](https://cloud.githubusercontent.com/assets/13781525/11739481/7d800ac2-9ff4-11e5-9d59-cdd9095d8dfb.png)

**Comment by marcushellberg** [comment] 2015-12-15 17:07
Not having a shadow is by design in the grid, so I don't feel like our demo should override that. If we think this is a usability problem, it would apply to all grids out there, and should be fixed in grid instead. 

Closing for now.

**Closed as completed by marcushellberg** 2015-12-15 17:07 UTC
